### PR TITLE
Add ly server (initial version)

### LINKED ISSUE #60: ly http-server
I'm considering to write a `ly` HTTP server but wanted to get some feedback before diving in.

Use cases/benefits for such a server mode are/include:

- "live" syntax highlighting on websites
- implementing lilypond code editors in browser (extension of first item)
- integrating `ly` in non-Python applications
- batch processing

The latter item is why I'm considering this. I want to rewrite my plugin that does the highlighting in the [LIlyPond Textbook](https://textbook.openlilylib.org), and instead of firing up the Python script for each LilyPond snippet I hope that it is more efficient to start a server at the beginning of that process and retrieve the highlighted data from that.  
If that works out it should be an option for building the LilyPond docs as well (I *really* would love seeing LilyPond's docs with highlighted code examples).

Any ideas, caveats, objections at this point?

### PR DESCRIPTION
**Pull request by uliska**
Closes #60

In its first version this server supports POST requests that trigger the ly commands just like the ly CLI script does.

There are some Python2/3 issues left, some discussion to be done and more functionality to be desired. In particular:

- Encoding problems with Python2/3
- Disambiguation of error reporting
- implementing the --timeout option (automatic shutdown)
- Add some GET routes for more interesting behaviour
  - /version (return ly version)
  - /stop (stop the server)
  - /timeout/N (modify the timeout)
  - etc?

### CODE REVIEW

**Comment by PeterBjuhr** [comment]
Unlike Gitlab, Github doesn't support `[WIP]` in the PR title. But I think it can be a good idea to use that convention anyway. What do you think?

(Your description mentions some todos but maybe they're intended for the next PR!?)

**Comment by uliska** [comment]
I don't mind discussing these todos and questions while reviewing and  before merging. But it would also work out to merge and then discuss them (in that case I'd create one or more issues).

But in principle I find it a very good approach to open pull requests with the intention to still work on the feature. Maybe if we would have a convention for that it would make one feel somewhat more comfortable sharing unfinished code.

**Comment by PeterBjuhr** [comment]
In Gitlab a WIP Merge Request (as they are called there) can't be merged (that's the support). I think the convention is the same here on Github except for the fact that the technically still can be merged.

Of course there can be review, discussion and further work on any PR. But with the WIP tag you're saying don't merge this - only (pre)review it. 

But perhaps you don't want to say that in this case (but as I recall you have in some past PR:s - back then I wasn't familiar with this convention).

**Comment by uliska** [comment]
In this case I didb't want to say that, rather raise the thought of it.  But in general it could be useful to agree upon either a tag or a naming convention.

We don't need a technical enforcement, though. As with our new "power" to push anything without review this can work smoothly based on agreement.

But back from the meta discussion to the original PR: What's with the ly-server code (and particularly with the midifications to ly.cli)?
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by uliska** [comment]
BTW @wbsoft: The first three commits and especially the second are relevant independently of the ly-server.

To test I suggest using a tool like the [HttpRequester](https://addons.mozilla.org/de/firefox/addon/httprequester/) Firefox extension or a similar tool.

**Comment by PeterBjuhr** [comment]
> We don't need a technical enforcement,[...] this can work smoothly based on agreement.

Agreed!

> But back from the meta discussion to the original PR: What's with the ly-server code (and particularly with the midifications to ly.cli)?

Alright. I have not full insight in this but one question comes easily to mind - why do you need to use (and change) the cli commands if this is not indended for command line usage?

**Comment by uliska** [comment]
In short: This is factoring out common functionality.

Basically the server uses the same commands as the CLI.
But the behaviour of the commands was inconsistent and partially incompatible with the server approach:

Basically commands take the cursor as argument and modify it in place, so subsequent commands work on the modified data. But there were some commands that immediately (i.e. within the function) wrote to stdout and some others wrote to file (or stdout if file is `-`). This doesn't work with a server that always has to assemble the modified document and send it back to the client.

The solution was to modify the commands (while making them behave consistently at the same time), so they now *all* modify the doc in-place. This is now consistent with both CLI and server. The CLI now implicitly adds commands to write to stdout and to file (whereas previously this only was the case with some of the file writing commands), while the server can take the modified data structure to compoes the HTTP response.

---

The other thing is: `Options` was factored out to be usable by both while `Output` was factored out because it is not used always, so it is only instantiated when there is actually the need.

**Comment by wbsoft** [comment]
There are some issues with the changes to the commands. I have not much time because of church services and recitals, but changing musicxml export to modify the document is not good, the original document should not change to an XML document (the musicxml export command is just an export command).

I think it is better to implement all the server stuff in `ly/server/` and not use the cli interface for server tasks.

**Comment by PeterBjuhr** [comment]
I agree with @wbsoft! And also I'm wondering if your approach with using `getattr `is completely safe...

**Comment by uliska** [comment]
I see your points but I'd still like to once more argue for my approach:

1)
I think it is a good idea if the `command` subclasses behave consistently. Currently (when I say 'currently' I mean current `master`) we have three behaviours: 

- `info_command`: write to stdout
- `edit_command`: modify cursor and imply `write` as last command (but only if the last command is an edit command)
- `export_command`: write to output (i.e. a file or stdout)

2)
I think it is good when the `command`s can be used by both `ly.cli.main` and `ly.server.main`. Otherwise we'd have to duplicate so much code and add possible new command in several places.

3)
Letting export commands change the document may introduce inconsistent results, yes. But already now the user can do that: when an edit command follows an export command but the last command is an info command (e.g. `"musicxml; transpose c d; mode"`).
I think we should rather handle the situation by enforcing the sequence of commands:
- There must be not more than one export command
- If there is an export command it must come last

This way we can have the result of the operation(s) in a consistent place (the `data` dict) to be used properly by either the CLI or the server (or maybe future ideas that might use it).

---

I think the `hasattr` approach is basically what we already have, only with the difference that I "ask" before accessing an attribute instead of just doing it and catching the exception.

**Comment by uliska** [comment]
We could make it even more consistent and flexible if you want to have (keep) the ability to have multiple export commands in one invocation:

* Pass along a `data` structure with *three* fields:
  * `cursor`, the ly.document.Cursor instance
  * `exports`, an array
  * `info`, an array

What happens is:

* Edit commands update the `cursor`
* Info commands append an entry to `info`
* Export commands append an entry to `exports`

Finally the fields are processed in the following way:

* If there are `info` entries they are printed to stdout
* If there are `exports` entries they are written to whatever `output` does (stdout or file(s))
* If there are Edit commands present but no Export commands `cursor` is written to `output`

That way we could have arbitrary combinations of the three command types without them interfering. (Of course the user can still write an export *first* and *then* an edit that would vanish. But *this* is really something we can ask from the user.)
The plus is that the commands behave consistently and can be invoked by different clients (currently: ly.cli.main and ly.server.main).

What do you think?

**Comment by PeterBjuhr** [comment]
> I think the hasattr approach is basically what we already have, only with the difference that I "ask" before accessing an attribute instead of just doing it and catching the exception.

Yes it's very similar but as I see it the security concerns when you're dealing with commands send through a server request are on a totally different level. But I'm no security expect so I can't judge if the approach really is an issue.

**Comment by PeterBjuhr** [comment]
> I think it is good when the commands can be used by both ly.cli.main and ly.server.main. Otherwise we'd have to duplicate so much code and add possible new command in several places.

I can see your motivation here but If you look at it from the other way around the code has to be maintained with both applications in mind. Which would be more complex than maintaining a set of commands with only one clear application.

With the changes you are proposing you have already proven that the two applications are somewhat different from the start and when in actual use I can easily see them diverge even more. Perhaps not to a point where the idea of common commands would become totally nonsensical but nevertheless.

**Comment by wbsoft** [comment]
I agree with @PeterBjuhr . Adding a common foundation layer to cli and server might save some duplicate (small) code parts (mainly those in `ly.cli.command`), but adds complexity and makes it necessary to maintain both server and cli code.

Please keep `ly.cli` as it is. It just serves the command line interface of the `ly` command.

What you could do is implement the server infrastructure the way you propose (but not alter `ly.cli`). Then, at a later stage, when the server stuff is working well, we (I) could decide to refactor `ly.cli` to use the common code. Only at that stage we could move some code to a common module, that then is used by both cli and server.

So first implement new stuff without altering existing and working parts. Only then optimize by looking at possible shareable infrastructure.

One of the design principles I (try to) use in Frescobaldi and Python-ly, is that new functionality can be added by only adding files or methods, and that it never should be necessary to alter existing code.

**Pull request closed without merging**
