### PR TITLE
Musicxml clefs

### PR DESCRIPTION
**Pull request by uliska**
This is not complete (see commit message for d6e2bcb41c78031cf47388358977f0c34b64691a) but partially solves #33 .
The issue of the two-octave shifts seems to be handled, and I have added the missing clefs to the clefnames dictionary. But the unknown clefs don't even reach that point because they are not recognized at some earlier point.

### CODE REVIEW

**Comment by uliska** [comment]
I started to look around the source files, but I don't seem to be able to progress here.

I think the PR can safely be merged. While not really solving the whole issue #33 there should be no side effects.

**Comment by PeterBjuhr** [comment]
The `Clef._specifier` property in the `ly.music` tree doesn't seem to be set for the clefs you mention. Perhaps they are missing already in the lexer!?

**Comment by uliska** [comment]
Yes, that's what I assume.
This is why they aren't highlighted in Frescobaldi's editor.
So they are probably newer in LilyPond and not updated with Frescobaldi.

Well, Frescobaldi explicitly supports the "current stable" version of 
LilyPond so far, and thus retrieves its syntax information from the 
respective files. I think it has been discussed to make this more open 
so Frescobaldi could support more versions. But as it stands I'd say 
python-ly simply doesn't support these clefs yet.
But on the bright side I'd say we have prepared that for musicxml 
export, and when the syntax definitions will get updated the clefs 
should work out-of-the-box.

**Comment by PeterBjuhr** [comment]
I agree! I think we can close #33 as this was about the export. Feel free to open a new issue about the general support.

**Pull request merged**
