### PR TITLE
MusicXML: Fix slurs over bars and voices

### PR DESCRIPTION
**Pull request by eoma**
These changes should make it possible keep slurs over multiple bars and merge other voices with slurs in a ScoreSection.

Tests are added, but the test script must be modified (not pushed here) in order to run on my machine (Ubuntu 16.10, python 3.5).

### CODE REVIEW

**Comment by wbsoft** [comment]
Thank you! @PeterBjuhr can you comment?
Just a little question of mine: why can't the `SlurCount` simply be an integer, using `+=1` and `-=1` to maintain the count? It seems overkill to use a SlurCount object with inc and dec methods. But maybe you want to extend SlurCount's functionality later?

**Comment by eoma** [comment]
SlurCount can't be an integer due to python's pass by value (copy). This means it's not possible to just pass along an integer expecting the function to modify it by reference, the alternative would be to modify and return the modified value. By using an object instance, only the pointer is copied, but I can still modify the instance.

I could remove the inc and dec methods, and just make its users modify count directly.

**Comment by wbsoft** [comment]
Ah, that's clear! No it's perfectly to keep it, then. As @PeterBjuhr  is the MusicXML man, I'll wait his response ;)

**Comment by eoma** [comment]
Rebased against latest release

**Comment by eoma** [comment]
I've added phrasing indication to the slur object.
This will later be useful for aligning lyrics to melody.

**Comment by eoma** [comment]
Any update on this?

**Comment by uliska** [comment]
I've merged master into this branch to fix a merge conflict.

Looking at the test files and briefly on the code I don't see anything that speaks against merging this, @PeterBjuhr

**Pull request merged**
